version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service_db
    ports:
      - "3307:3306"
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

  eurekaserver:
    build:
      context: ./eurekaserver
    container_name: eurekaserver
    ports:
      - "8765:8765"
    networks:
      - backend
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    depends_on:
      - mysql

  apigateway:
    build:
      context: ./apigateway
    container_name: apigateway
    ports:
      - "9090:9090"
    networks:
      - backend
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8765/eureka/
    depends_on:
      - eurekaserver

  userservice:
    build:
      context: ./userservice
    container_name: userservice
    ports:
      - "9091:9091"
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user_service_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8765/eureka/
    depends_on:
      - mysql
      - eurekaserver

networks:
  backend:

volumes:
  mysql_data:
