spring:
  application:
    name: userservice

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_service_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
 client:
    service-url:
      defaultZone: http://localhost:8765/eureka
 instance:
   ip-address: 127.0.0.1
   prefer-ip-address: true
   instance-id: ${spring.application.name}:${server.port}

#    hikari:
#      connection-timeout: 30000
#      maximum-pool-size: 10
#      minimum-idle: 5
#      idle-timeout: 300000
#      max-lifetime: 1200000
#      auto-commit: true

#  management:endpoints:web:exposure:include: health,info
#server:
#  port: 9091
#  servlet:
#    context-path: /api/users

#eureka:
# client:
#  service-url:
#    defaultZone: http://localhost:8765/eureka
#
#    instance:
#       lease-expiration-duration-in-seconds=180
#       lease-expiration-duration-in-seconds=180
#      ip-address: 127.0.0.1
#      prefer-ip-address: true
#      instance-id: ${spring.application.name}:${server.port}











